development:
  adapter: postgresql
  encoding: unicode
  database: gym_development
  pool: 5
  host: localhost
  username: tjegels
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gym_test
  pool: 5
  host: localhost
  username: tjegels
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gym_production
  pool: 5
  username: postgres
  password:
