Motivation.delete_all
Motivation.create(rating: 1, quote: "Be kind whenever possible. It is always possible.")
Motivation.create(rating: 3, quote: "If you're going through hell, keep going.")
Motivation.create(rating: 3, quote: "Believe in yourself! Have faith in your abilities!")
Motivation.create(rating: 2, quote: "Always do your best. What you plant now, you will harvest later.")
Motivation.create(rating: 3, quote: "Act as if what you do makes a difference. It does.")
Motivation.create(rating: 1, quote: "Either you run the day or the day runs you.")
Motivation.create(rating: 3, quote: "Strength does not come from physical capacity. It comes from an indomitable will.")
Motivation.create(rating: 2, quote: "Motivation is what gets you started. Habit is what keeps you going.")
Motivation.create(rating: 1, quote: "The secret of getting ahead is getting started.")